apiVersion: v1
kind: Service
metadata:
  namespace: default # Add this line
  name: randomhack-portal-service # Renamed service
spec:
  selector:
    app: randomhack-portal # Updated selector label
  ports:
    - protocol: TCP
      port: 80 # Port the service will listen on within the cluster
      targetPort: 80 # Port the container (Nginx) is listening on (from Deployment/Dockerfile)
  type: ClusterIP # Exposes the service on a cluster-internal IP. Only reachable from within the cluster.
                 # Use NodePort or LoadBalancer if you need direct external access without Ingress.