name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main # Or your primary deployment branch

env:
  # Define the image name. Adjust <YOUR_GITHUB_USERNAME> and <YOUR_REPOSITORY_NAME>
  # Example: ghcr.io/my-org/my-repo
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read       # Needed to check out the repository
      packages: write      # Needed to push packages (Docker images) to GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          # GITHUB_TOKEN is automatically created by Actions, needs permissions defined above
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          # Tag the image with the Git SHA and 'latest'
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.IMAGE_NAME }}:latest
          # Enable build cache for faster builds (optional)
          cache-from: type=gha
          cache-to: type=gha,mode=max